# .golangci.yml
version: "2"

linters:
  default: none
  enable:
    - loglinter
  settings:
    custom:
      loglinter:
        type: module
        description: Checks log messages.
        settings:
          enabled: true
          enable_lowercase:   true
          enable_english:     true
          enable_specchars:   true
          enable_sensitive:   true
          enable_custom:      true
          words:
              - "internal"
              - "secret"
              - "debug_mode"
          patterns:
            - "credit.?card"
            - "social.?security"