# .golangci.yml
version: "2"

linters:
  default: none
  enable:
    - loglinter
  settings:
    custom:
      loglinter:
        type: "module"
        description: Checks log messages.
        settings:
        forbidden-patterns:
          - "credit.?card"
          - "social.?security"
        forbidden-words:
          - "internal"
          - "ssn"
          - "debug_mode"